# Generated by Django 5.0.4 on 2024-09-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_doctor_doctoravailability_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('current_sugar_rate', models.IntegerField(blank=True, null=True)),
                ('pressure', models.IntegerField(blank=True, null=True)),
                ('disease_affected', models.CharField(max_length=200)),
                ('tablets_taken', models.CharField(blank=True, max_length=200)),
                ('age_category', models.CharField(choices=[('teen', 'Teen'), ('elder', 'Elder'), ('old_age', 'Old Age')], max_length=20)),
            ],
        ),
    ]
