# Generated by Django 5.0.4 on 2024-09-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age_category',
            field=models.CharField(choices=[('teen', 'Teen'), ('elder', 'Elder'), ('old_age', 'Old Age')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='current_sugar_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='disease_affected',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pressure',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
