# Generated by Django 5.0.4 on 2024-09-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_patient_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('sugar_rate', models.FloatField()),
                ('pressure', models.FloatField()),
                ('disease_affected', models.CharField(max_length=200)),
                ('curability_level', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
