# Generated by Django 5.0.4 on 2024-09-29 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_patientdata_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdata',
            old_name='curability_level',
            new_name='cholesterol_level',
        ),
    ]
